### ISSUE TITLE
Documentation or example code ?

### ISSUE THREAD

**Issue by GreggAtRodale** [brightcove/PHP-API-Wrapper#12]
I'm trying to convert some code we had that used the old BC-Mapi API library to use the new PHP-API-Wrapper API Library and am getting stuck on how this all works.  Our existing code queried for new videos and changed videos at Brightcove and pulled down lists of those videos which we then used to create Drupal content that could drive things like listings of video content on certain pages on our sites.  

Are there any examples or documentation available at all for this new PHP-API-Wrapper library ?  The php-unit test code is of no help to me in understanding this and there has been really limited code cited in the four issues entered so far.  Anything would be greatly appreciated.  Thanks.

**Comment by janmashat** [comment]
We rely extensively on this PHP-API-Wrapper library in the 7.x-6.x and 8.x-1.x versions of the Brightcove module for Drupal, so you should be able to find many examples there: https://www.drupal.org/project/brightcove If you require additional support, please contact your Brightcove account manager.

**Comment by chriscohen** [comment]
So where's the documentation? I can't find any anywhere. The Brightcove Drupal project is no help because it assumes you just want to add a video field or make views. I'm trying to interact directly with the API.

Has this entire API library been released with no documentation? "Ask your account manager" is not really an answer.

Sure, I could write my own API integration using PHP and curl, but the point of this library is to abstract some of this so that my life is easier. But if I don't understand how to use it without studying all the code, it's going to be a huge struggle.

**Comment by janmashat** [comment]
Unfortunately we haven't been able to cover documentation in the sprints up until now, but it’s certainly something we will try to include in the upcoming sprints - hopefully later this year. If it helps - in the short term - this entire library mirrors the Brightcove API structure, and that is well documented.
