### ISSUE TITLE
CMS API getVideoSource , Source class does not have the src param

### ISSUE THREAD

**Issue by sasiarjun** [brightcove/PHP-API-Wrapper#9]
We tried to get the video source renditions, So we used the getVideoSource function, Its giving all output except src values.
In the brightcove documentation there available "src" param in video source but we couldn't find in php api.
"src" : "http://brightcove.vo.llnwd.net/e1/uds/pd/1507807800001/1507807800001_2114524848001_Bird-Titmouse7.mp4",

http://docs.brightcove.com/en/video-cloud/cms-api/guides/retrieve-video-data.html#sourcesEndpoint

1. How can we get "src" param using php api?
2. Is there any alternative ways to get src in php api?

**Comment by sasiarjun** [comment]
Please help me to solve this? Is there any plan to update the this api

**Comment by janmashat** [comment]
We will add this during the next release, but have no ETA at the moment. Please contact your Brightcove account manager if this is a high priority request.

**Comment by skynet** [comment]
Does that mean that we cannnot get the source URL through the API?

**Comment by GreggAtRodale** [comment]
I built this into ours because we needed it as well.  

Since 'src" is actually in the JSON returned you just need to process it like all the other fields in the JSON get processed, so in source.php in function applyJSON() I added:

$this->applyProperty($json, 'src');

Then at the end of source.php I added the getters and setters:
  /**
   * @return string
   */
  public function getSrc() {
    return $this->src;
  }

  /**
   * @param string $src
   * @return Source
   */
  public function setSrc($src) {
    $this->src = $src;
    $this->fieldChanged('src');
    return $this;
  }

**Comment by tamasd** [comment]
The current release contains this. I forgot to close this ticket.

**Comment by skynet** [comment]
Why don't you write some code sample? Thanks.

**Comment by janmashat** [comment]
Please see the code here: http://cgit.drupalcode.org/clarify/tree/clarify_brightcove/clarify_brightcove.module?h=7.x-1.x
